import { useState } from "react";
import { motion } from "framer-motion";
import { ScrollText, Shield, RefreshCw, ChevronRight } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

type LegalTab = "terms" | "privacy" | "refund";

const TABS: { id: LegalTab; Icon: React.ElementType; label: string }[] = [
  { id: "terms", Icon: ScrollText, label: "Terms of Service" },
  { id: "privacy", Icon: Shield, label: "Privacy Policy" },
  { id: "refund", Icon: RefreshCw, label: "Refund Policy" },
];

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <div className="mb-8">
    <h3 className="text-base sm:text-lg font-bold mb-3" style={{ color: "hsl(158, 38%, 15%)" }}>{title}</h3>
    <div className="text-sm leading-relaxed space-y-2" style={{ color: "hsl(158, 18%, 40%)" }}>
      {children}
    </div>
  </div>
);

const Legal = () => {
  const [tab, setTab] = useState<LegalTab>("terms");

  return (
    <div className="min-h-screen relative overflow-x-hidden">
      <div className="fixed inset-0 pointer-events-none z-0">
        <div className="ambient-orb-1" style={{ top: "8%", right: "10%", opacity: 0.5 }} />
      </div>
      <Navbar />

      <section className="relative pt-32 pb-12 px-4 sm:px-6 lg:px-8 z-10 text-center">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass-panel mb-5 text-xs font-medium"
            style={{ color: "hsl(158, 38%, 28%)" }}>
            <ScrollText className="w-3.5 h-3.5 text-primary" />
            Legal & Policies
          </div>
          <h1 className="text-4xl sm:text-5xl font-heading tracking-tight mb-4" style={{ color: "hsl(158, 45%, 10%)" }}>
            Legal <span className="text-mint-gradient">Pages</span>
          </h1>
          <p className="text-muted-foreground max-w-lg mx-auto text-sm">Last updated: February 2026</p>
        </motion.div>
      </section>

      <section className="relative z-10 px-4 sm:px-6 lg:px-8 pb-20">
        <div className="max-w-4xl mx-auto">

          {/* Tab nav */}
          <div className="flex gap-2 mb-8 overflow-x-auto pb-1">
            {TABS.map(t => {
              const active = tab === t.id;
              return (
                <button key={t.id} onClick={() => setTab(t.id)}
                  className={`flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium whitespace-nowrap transition-all
                    ${active ? "bg-primary text-primary-foreground shadow-md" : "glass-panel text-muted-foreground hover:text-foreground"}`}>
                  <t.Icon className="w-4 h-4" />
                  {t.label}
                </button>
              );
            })}
          </div>

          <motion.div
            key={tab}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.3 }}
            className="glass-panel rounded-3xl p-6 sm:p-10"
          >
            {/* TERMS */}
            {tab === "terms" && (
              <>
                <h2 className="text-2xl font-heading mb-6" style={{ color: "hsl(158, 45%, 10%)" }}>Terms of Service</h2>
                <Section title="1. Acceptance of Terms">
                  <p>By accessing or using KroTravel ("Service"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.</p>
                </Section>
                <Section title="2. Description of Service">
                  <p>KroTravel provides AI-powered travel itinerary generation, memory storage, and travel planning tools. The Service includes both free and paid tiers with different feature levels.</p>
                </Section>
                <Section title="3. User Accounts">
                  <p>You are responsible for maintaining the confidentiality of your account. You agree to provide accurate information and to update it as needed. You may not share your account with others.</p>
                </Section>
                <Section title="4. Paid Services">
                  <p>Certain features require payment. All payments are processed securely. Once an itinerary is generated and delivered, it is considered fulfilled. See our Refund Policy for exceptions.</p>
                </Section>
                <Section title="5. AI-Generated Content">
                  <p>Itineraries are generated by AI and are for planning purposes only. While we strive for accuracy, KroTravel cannot guarantee the availability of places, prices, or transport options listed. Always verify critical details before travel.</p>
                </Section>
                <Section title="6. Prohibited Use">
                  <p>You may not use KroTravel to scrape content, reverse-engineer the AI, resell itineraries commercially, or engage in fraudulent activities. Violations may result in account termination.</p>
                </Section>
                <Section title="7. Limitation of Liability">
                  <p>KroTravel is not liable for any travel disruptions, losses, or damages arising from reliance on AI-generated itineraries. Use our content as a starting point, not a guarantee.</p>
                </Section>
                <Section title="8. Changes to Terms">
                  <p>We reserve the right to update these Terms. Continued use of the Service after changes constitutes acceptance of the new Terms.</p>
                </Section>
                <Section title="9. Contact">
                  <p>For questions about these Terms, contact us at <span className="text-primary">support@krotravel.com</span></p>
                </Section>
              </>
            )}

            {/* PRIVACY */}
            {tab === "privacy" && (
              <>
                <h2 className="text-2xl font-heading mb-6" style={{ color: "hsl(158, 45%, 10%)" }}>Privacy Policy</h2>
                <Section title="1. What We Collect">
                  <p>We collect information you provide directly (name, email, travel preferences) and information generated by your use of our Service (itineraries, photos uploaded to Memory Vault).</p>
                </Section>
                <Section title="2. How We Use It">
                  <ul className="list-disc list-inside space-y-1">
                    <li>To generate personalized travel itineraries</li>
                    <li>To save and retrieve your trips and memories</li>
                    <li>To improve our AI models (anonymized, aggregated)</li>
                    <li>To send you service-related communications (not marketing spam)</li>
                  </ul>
                </Section>
                <Section title="3. What We Don't Do">
                  <p>We do not sell your data to third parties. We do not use your personal travel plans for advertising profiling. We do not share your information without your consent except as required by law.</p>
                </Section>
                <Section title="4. Data Storage">
                  <p>Your data is stored securely using industry-standard encryption. Photos uploaded to Memory Vault are stored in private, access-controlled cloud storage accessible only by you.</p>
                </Section>
                <Section title="5. Data Retention">
                  <p>We retain your account data for as long as your account is active. You may request deletion of your account and associated data by contacting support.</p>
                </Section>
                <Section title="6. Cookies">
                  <p>We use minimal, essential cookies for authentication and session management. We do not use tracking or advertising cookies.</p>
                </Section>
                <Section title="7. Your Rights">
                  <p>You have the right to access, correct, or delete your personal data. Contact <span className="text-primary">support@krotravel.com</span> to exercise these rights.</p>
                </Section>
                <Section title="8. Contact">
                  <p>Privacy concerns: <span className="text-primary">support@krotravel.com</span></p>
                </Section>
              </>
            )}

            {/* REFUND */}
            {tab === "refund" && (
              <>
                <h2 className="text-2xl font-heading mb-6" style={{ color: "hsl(158, 45%, 10%)" }}>Refund Policy</h2>
                <div className="rounded-xl bg-primary/5 border border-primary/20 p-4 mb-6 text-sm" style={{ color: "hsl(158, 38%, 25%)" }}>
                  <p className="font-semibold mb-1">Our core commitment:</p>
                  <p>If our AI fails to deliver a usable itinerary, you get a full refund. No questions asked.</p>
                </div>
                <Section title="1. Eligible Refunds">
                  <ul className="list-disc list-inside space-y-1">
                    <li>AI generation failed or returned an empty/broken itinerary</li>
                    <li>Technical error prevented delivery of the paid product</li>
                    <li>Duplicate payment charged in error</li>
                  </ul>
                </Section>
                <Section title="2. Non-Refundable Cases">
                  <ul className="list-disc list-inside space-y-1">
                    <li>Itinerary was successfully generated but you changed your mind</li>
                    <li>You found the itinerary unhelpful after reading it fully</li>
                    <li>Trip was cancelled due to personal reasons</li>
                    <li>Preferences entered incorrectly by the user</li>
                  </ul>
                </Section>
                <Section title="3. How to Request a Refund">
                  <p>Contact us at <span className="text-primary">support@krotravel.com</span> within 48 hours of purchase with your trip ID and a description of the issue. We review all requests within 24 hours.</p>
                </Section>
                <Section title="4. Processing Time">
                  <p>Approved refunds are processed within 5–7 business days back to the original payment method.</p>
                </Section>
                <Section title="5. Premium Subscriptions">
                  <p>Annual Premium (Nomad) subscriptions are non-refundable after 14 days of activation, as the features are immediately available in full.</p>
                </Section>
                <Section title="6. Contact">
                  <p>Refund requests: <span className="text-primary">support@krotravel.com</span></p>
                </Section>
              </>
            )}
          </motion.div>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default Legal;
